### ISSUE TITLE
nativescript-vue integration - can't figure this out

### ISSUE THREAD

**Issue by envisean** [papmodern/nativescript-cognito#1]
I seem to be able to add the plugin to my project perfectly fine, and it's not throwing errors. The issues come in when I'm trying to use the plugin to authenticate (I don't seem to get many errors either when testing, so it's hard for me to tell if the connection is working or not).

Here's a code sample in how I'm integrating into my `main.js` just for testing purposes from a `nativescript-vue` project:

Placed this at the top with my other imports:
`import { Cognito } from 'nativescript-cognito'`

Then somewhere in the file just to kick out some logging...
```let cogn = new Cognito('us-west-POOLID', '3arCLIENTID')
async function login() {
  console.log('[ATTEMPTING TO LOGIN...]')
  let sean = await cogn.authenticate('sean@emaildomain.com', 'SupersecretPassword')
  console.log('[Cognito Auth After] ', sean)
}
login()```

Is there any way to get a deeper level of debugging or is there something that's wrong here?

**Comment by papmodern** [comment]
You can use try/catch to catch exceptions

    async function login() {
      console.log('[ATTEMPTING TO LOGIN...]')
      try {
          let sean = await cogn.authenticate('sean@emaildomain.com', 'SupersecretPassword')
          console.log('[Cognito Auth After] ', sean)
      catch (e) {
          console.log('[Cognito Auth Error] ', e)
      }
    }
    login()
