### ISSUE TITLE
refreshing tokens

### ISSUE THREAD

**Issue by westlakem** [papmodern/nativescript-cognito#2]
I can't figure out how to use the refresh token.

When you authenticate, you're given an access token and a refresh token.  I cannot figure out how to see if the access token is valid, and if not, use the refresh token to get a new token pair.

**Comment by baart1989** [comment]
Hi

I am having similar problem as @westlakem.

According to following [stackoverflow](https://stackoverflow.com/questions/39111995/cognito-user-pool-how-to-refresh-access-token-android) 

"When you call getSession(...) - to get tokens - and if the cached tokens have expired, the SDK will automatically refresh tokens (as long as the refresh token has not expired)."

However for me tokens are not refreshed, not sure why.

@papmodern would be able to expose refreshToken function from SDK ?

As we have access to refresh token we would be able to do smth like:
`this._cognito.refreshSession(refreshToken, (err: any, newSession: CognitoUserSession) => {});`
