### ISSUE TITLE
How to change region

### ISSUE THREAD

**Issue by skhye05** [papmodern/nativescript-cognito#3]
Hi, i would like to know if it's possible to change the region, i have seen it being done on the android SDK example but with the plugins i don't know how to do it.
Can you please help?

**Comment by baart1989** [comment]
Hi

It can be done, but with this plugin it is hardcoded to us-east-1.

@papmodern would you be able to provide option to pass region when initialising Cognito ?

**Comment by papmodern** [comment]
Thanks to @skhye05, related commit 48f4ac2 merged to master branch and npm will be updated in few hours.
